trigger:
  branches:
    include:
      - main
  paths:
    include:
      - dev/**
      - qa/**
      - PreProd/**
      - Prod/**

variables:


stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        displayName: 'Deploy Infrastructure to Azure'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              cd dev
              terraform init
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Deploying'
